// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffaalgyhvutfoooxquab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmYWFsZ3lodnV0Zm9vb3hxdWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MDA5OTIsImV4cCI6MjA1MzE3Njk5Mn0.Rl9m-g1am0hAzrNsAUb1Wz72dtW1iSv00aVhLWyFf8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);